config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  root 'homes#top'
  get 'home/about', to: 'homes#about', as: 'about'
  
  resources :posts do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites,only: [:create, :destroy]
  end
  resources :favorites, only: [:index]


  resources :users, only: [:index, :show, :edit, :update,:destroy] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  get '/search', to: 'searches#search'

  
  devise_for :admin_users, path: 'admin', controllers: {
    sessions: 'admin/sessions'
  }
  
  namespace :admin  do
    resources :dashboard, only: [:index, :show, :destroy] 
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

	def search
		@model = params[:model]
		@content = params[:content]
		@method = params[:method]

	  if @model == 'post'
      @results = Post.search_for(@content, @method)
    elsif @model == 'user'
      @results = User.search_for(@content, @method)
    else
      @results = []
		end
	end
end

app/views/searches/_form.html.erb
<% if user_signed_in? %>
  <%= form_with url: search_path, method: :get, local: true do |f| %>
    <div class="mb-3">
      <%= f.label :model, '検索対象',class: 'form-label' %>
      <%= f.select :model, [['ユーザー', 'user'], ['投稿', 'post']],{},class: 'form-select' %>
    </div>
    <div class="mb-3">
      <%= f.label :content, 'キーワード',class:'form-label' %>
      <%= f.text_field :content, class: 'form-control' %>
    </div>
    <%= f.submit '検索',class:'btn btn-primary' %>
  <% end %>
<% end %>

app/views/searches/search.html.erb
<h1 class="mb-4">検索結果</h1>
<div class="container">
<% if @model == 'user' %>
  <h3>Users search for "<%= @content %>"</h3>
  <% if @results.present? %>
    <ul class="list-group">
      <% @results.each do |user| %>
        <li class="list-group-item">
        <%= link_to user.name, user_path(user) %>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>No users found.</p>
  <% end %>
<% elsif @model == 'post' %>
  <h3>Posts search for "<%= @content %>"</h3>
  <% if @results.present? %>
    <ul class="list-group">
      <% @results.each do |post| %>
        <li class="list-group-item">
          <strong><%= link_to post.title, post_path(post) %></strong>
          <p><%= post.content %></p>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>No posts found.</p>
  <% end %>
<% end %>
</div>