config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  root 'homes#top'
  get 'home/about', to: 'homes#about', as: 'about'
  
  resources :posts do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites,only: [:create, :destroy]
  end
  resources :favorites, only: [:index]


  resources :users, only: [:index, :show, :edit, :update,:destroy] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  get '/search', to: 'searches#search'

  
  devise_for :admin_users, path: 'admin', controllers: {
    sessions: 'admin/sessions'
  }
  
  namespace :admin  do
    resources :dashboard, only: [:index, :show, :destroy] 
  end
end

app/models/post.rb
class Post < ApplicationRecord
  
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites,dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  validates:title,presence:true, length:{maximum:50}
  validates:content,presence:true,length:{maximum:200}
 
  def self.search_for(content, method)
    if method == 'perfect'
      Post.where(title: content)
    elsif method == 'forward'
      Post.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Post.where('title LIKE ?', '%'+content)
    else
      Post.where('title LIKE ?', '%'+content+'%')
    end
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update,:destroy ]

  def index
    @posts = current_user.feed
    @post = Post.new
    @user = current_user
  end

  def show
    @post = Post.find(params[:id])
    @new_post = Post.new
    @user = @post.user
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:notice] = "投稿が保存されました。"
      redirect_to post_path(@post)
    else
     flash[:alert] = "投稿の保存に失敗しました。"
      @posts = Post.all
      @user = current_user
      render :index
    end
  end

  def edit
    @post = Post.find(params[:id])
    if @post.user !=current_user
     flash[:alert] = "編集する権限がありません。"
    redirect_to posts_path 
  end
end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "投稿が更新されました。"
      redirect_to post_path(@post)
    else
      flash[:alert] = "投稿の更新に失敗しました。"
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.user == current_user
    if @post.destroy
      flash[:notice] = "投稿が削除されました。"
      redirect_to posts_path
    else
      flash[:alert] = "投稿の削除に失敗しました。"
      redirect_to posts_path
    end
  else
    flash[:alert] = "他のユーザーの投稿は削除できません。"
    redirect_to posts_path
   end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def ensure_correct_user
    @post = Post.find(params[:id])
    unless @post.user == current_user
      flash[:alert] = "権限がありません。"
      redirect_to posts_path
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="container">
  <h1>投稿編集</h1>
  
      <% if @post.errors.any?%>
      <div class="alert alert-danger">
         <%= pluralize(@post.errors.count, "error") %> prohibited this book from being saved:
         <ul>
            <% @post.errors.full_messages.each do |message| %>
            <li><%=message%></li>
            <%end%>
         </ul>
      </div>
      <%end%>
  
  <%=form_with model:@post,local: true  do |f|%>
  <div class="mb-3">
    <%=f.label :title, "タイトル",class: 'form-label'%>
    <%=f.text_field :title, class: 'form-control'%>
  </div>
  
  <div class="mb-3">
    <%=f.label :content,"内容",class: 'form-label'%>
    <%=f.text_area :content,class: 'form-control'%>
  </div>
  
  <div class="mb-3">
    <%=f.submit "更新",class: 'btn btn-primary'%>
    <%=link_to '詳細へ',post_path(@post),class: 'btn btn-secondary'%>
    <%=link_to '戻る',posts_path,class: 'btn btn-secondary'%>
    <%= link_to '削除', post_path(@post),  method: :delete,  class: 'btn btn-danger', data: { confirm: "本当に削除しますか？" } %>
  </div>
  <%end%>
</div>


















  
  

app/views/posts/index.html.erb
<div class="container mt-4">
  <% if @post.errors.any?%>
  <div class="alert alert-danger">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this book from being saved:</h2>
    <ul>
       <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    </div>
    <%end%>
  
    
  <div class="mb-5">
  <h2 class="mb-4">新規投稿</h2>
<%=form_with model: @post,local: true do |f|%>
<div class="mb-3">
 <%=f.label :title,"タイトル", class: 'form-label'%>
 <%=f.text_field :title,  class: 'form-control'%>
</div>
<div class="mb-3">
  <%=f.label :content,"内容",class: 'form-label'%>
  <%=f.text_area :content, class: 'form-control'%>
</div>
<div class="mb-3">
  <%=f.submit '投稿',class: 'btn btn-primary'%>
</div>
<%end%>
  
  <div class="mb-5">
    <h2 class="mb-3">自分とフォローしている人の投稿一覧</h2>
    <% if @posts.any? %>
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>画像</th>
          <th>タイトル</th>
          <th>内容</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @posts.each do |post|%>
        <tr>
          <td><%=image_tag post.user.get_profile_image(50,50)%> </td>
          <td><%=post.title%></td>
          <td><%=post.content%></td>
          <td><%=link_to '詳細へ',post_path(post),class: 'btn  btn-secondary  btn-sm mb-2 d-block'%></td>
         <td>
          <% unless post.user==current_user%>
          <% if post.favorited_by?(current_user)%>
          <%=link_to 'いいね解除',post_favorites_path(post),method: :delete, class: 'btn btn-danger btn-sm mb-2 d-block '%>
          <%else%>
          <%=link_to 'いいね',post_favorites_path(post),method: :post, class: 'btn btn-primary  btn-sm mb-2 d-block'%>
          <%end%>
         <%end%>
         <p class="mt-2">いいね数: <%=post.favorites.count%></p>
         </td>
        </tr>
        <%end%>
      </tbody>
    </table>
    <%else%>
     <p>フィードに表示する投稿が現在ありません。</p>
  <% end %>
  </div>
  </div>
  
  
  
  
  
  
  
  

  

app/views/posts/show.html.erb
<div class="container mt-4">
<% if @post.errors.any?%>
  <div class="alert alert-danger">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this book from being saved:</h2>
    <ul>
       <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    </div>
    <%end%>

  
  <div class="mb-5">
    <h2 class="mb-4">投稿の詳細</h2>
    <div class="table-responsive">
    <table class="table table-striped table-hover ">
    <thead>
      <tr>
      <th>画像</th>
      <th>名前</th>
      <th>タイトル</th>
      <th>内容</th>
      <th></th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td><%=image_tag @post.user.get_profile_image(50,50)%></td>
        <td><%=@post.user.name%></td>
        <td><%=@post.title%></td>
        <td><%=@post.content%></td>
        <td>
        <% if @post.user==current_user%>
        <%=link_to '編集',edit_post_path(@post),class: 'btn  btn-secondary btn-sm mb-2 d-block'%>
        <%end%>
        <% if current_user != @post.user%>
        <% if current_user.following?(@post.user) %>
        <%=link_to 'フォロー解除',user_relationships_path(@post.user.id),method: :delete, class: 'btn btn-info btn-sm mb-2 d-block' %>
        <% else%>
        <%=link_to 'フォロー',user_relationships_path(@post.user.id),method: :post, class: 'btn btn-success btn-sm mb-2 d-block' %>
        <%end%>
        <%end%>
        <% unless @post.user==current_user%>
       <% if @post.favorited_by?(current_user)%>
       <%=link_to 'いいね解除',post_favorites_path(@post),method: :delete, class: 'btn btn-danger btn-sm mb-2 d-block'%>
       <%else%>
       <%=link_to 'いいね',post_favorites_path(@post),method: :post, class: 'btn btn-primary btn-sm mb-2 d-block'%>
      <%end%>
      <%end%>
      <p class="mt-2">いいね数: <%=@post.favorites.count%></p>
      </td>
      </tr>
      </tbody>
    </table>
   </div>
   </div>
   
     
   <div class="mb-5">
    <h3 class="mb-3">コメントを投稿する</h3>
    <%=form_with(model: [@post,PostComment.new],local:true) do |f|%>
      <div class="mb-3">
      <%=f.text_area :comment,rows:'5',placeholder:"コメントをここに",class: 'form-control'%>
      </div>
      <div class="mb-3">
      <%=f.submit "送信",class: 'btn btn-primary'%>
      </div>
      <%end%>
      </div>


   <div class="mb-5">
   <h3 class="mb-4">コメントした人</h3> 
   <div class="table-responsive">
  <table class="table table-striped">
    <thead>
    <tr>
    <th>画像</th>
    <th>名前</th>
    <th>コメント</th>
    <th></th>
    </tr>
   </thead>
   <tbody>
<% @post.post_comments.each do |post_comment|%>
  <tr>
   <td><%= image_tag post_comment.user.get_profile_image(50, 50) %></td>
   <td> <%=link_to user_path(post_comment.user) do%>
     <%=post_comment.user.name%>
    <%end%>
    </td>
    <td><%=post_comment.comment%></td>
    <td>
    <% if post_comment.user==current_user%>
    <%= link_to "削除", post_post_comment_path(@post, post_comment), method: :delete, class: ' btn  btn-danger btn-sm' %>
    <%end%>
    </td>
    </tr>
    <%end%>
    </tbody>
    </table>
  </div>
</div>
</div>