config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  root 'homes#top'
  get 'home/about', to: 'homes#about', as: 'about'
  
  resources :posts do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites,only: [:create, :destroy]
  end
  resources :favorites, only: [:index]


  resources :users, only: [:index, :show, :edit, :update,:destroy] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  get '/search', to: 'searches#search'

  
  devise_for :admin_users, path: 'admin', controllers: {
    sessions: 'admin/sessions'
  }
  
  namespace :admin  do
    resources :dashboard, only: [:index, :show, :destroy] 
  end
end

app/views/layouts/_flash_messages.html.erb
<% if flash[:alert] %>
<div class="alert alert-danger">
  <%= flash[:alert] %>
</div>
<% end %>
<% if flash[:notice] %>
<div class="alert alert-success">
  <%= flash[:notice] %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lifenote</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Lifenote</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
           <% if admin_user_signed_in? %>
          <ul class="navbar-nav ms-auto">
            <li class="nav-item"><%= link_to '管理者ダッシュボード',admin_dashboard_index_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to '管理者ログアウト', destroy_admin_user_session_path, method: :delete, data: { confirm: 'ログアウトしますか？' }, class: 'nav-link' %></li>
          </ul>
        <% elsif user_signed_in? %>
          <ul class="navbar-nav ms-auto">
            <li class="nav-item"><%= link_to 'ホーム', user_path(current_user), class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'ユーザー', users_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to '投稿', posts_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'いいね一覧', favorites_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
          </ul>
        <% else %>
          <ul class="navbar-nav ms-auto">
            <li class="nav-item"><%= link_to 'ホーム', root_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'このサイトについて', about_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to '新規登録', new_user_registration_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'ログイン', new_user_session_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to '管理者ログイン', new_admin_user_session_path, class: 'nav-link' %></li>
          </ul>
        <% end %>
        
          </div>
        </div>
      </nav>
      <div class="container mt-3">
        <%= render 'searches/form' %>
      </div>
    </header>

    <div class="container mt-3">
    <%=render 'layouts/flash_messages'%>
    </div>

    <main class="container mt-4">
    <%= yield %>
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>